import { LiteratureType } from './literature.types';

export const literatures: LiteratureType[] = [
  {
    imageSrc: '/images/libro1.jpg',
    marketSrc: 'https://tienda.juanrocha.co/',
    preview: [
      '/images/el-ahorcado/1.jpg',
      '/images/el-ahorcado/2.jpg',
      '/images/el-ahorcado/3.jpg',
      '/images/el-ahorcado/4.jpg',
      '/images/el-ahorcado/5.jpg',
      '/images/el-ahorcado/6.jpg',
      '/images/el-ahorcado/7.jpg',
      '/images/el-ahorcado/8.jpg',
      '/images/el-ahorcado/9.jpg',
      '/images/el-ahorcado/10.jpg',
    ],
    title: 'EL AHORCADO',
  },
  {
    imageSrc: '/images/libro2.jpg',
    marketSrc: 'https://tienda.juanrocha.co/',
    preview: [
      '/images/los-descorazados/1.jpg',
      '/images/los-descorazados/2.jpg',
      '/images/los-descorazados/3.jpg',
      '/images/los-descorazados/4.jpg',
      '/images/los-descorazados/5.jpg',
      '/images/los-descorazados/6.jpg',
      '/images/los-descorazados/7.jpg',
      '/images/los-descorazados/8.jpg',
      '/images/los-descorazados/9.jpg',
      '/images/los-descorazados/10.jpg',
      '/images/los-descorazados/11.jpg',
      '/images/los-descorazados/12.jpg',
    ],
    title: 'LOS DESCORAZADOS',
  },
  {
    imageSrc: '/images/libro3.jpg',
    marketSrc: 'https://tienda.juanrocha.co/',
    preview: [
      '/images/los-acorazados/1.jpg',
      '/images/los-acorazados/2.jpg',
      '/images/los-acorazados/3.jpg',
      '/images/los-acorazados/4.jpg',
      '/images/los-acorazados/5.jpg',
      '/images/los-acorazados/6.jpg',
      '/images/los-acorazados/7.jpg',
      '/images/los-acorazados/8.jpg',
      '/images/los-acorazados/9.jpg',
      '/images/los-acorazados/10.jpg',
    ],
    title: 'LOS ACORAZADOS',
  },
  {
    imageSrc: '/images/libro4.jpg',
    marketSrc: 'https://tienda.juanrocha.co/',
    preview: [
      '/images/no-digas-nada/1.jpg',
      '/images/no-digas-nada/2.jpg',
      '/images/no-digas-nada/3.jpg',
      '/images/no-digas-nada/4.jpg',
      '/images/no-digas-nada/5.jpg',
      '/images/no-digas-nada/6.jpg',
      '/images/no-digas-nada/7.jpg',
      '/images/no-digas-nada/8.jpg',
      '/images/no-digas-nada/9.jpg',
      '/images/no-digas-nada/10.jpg',
      '/images/no-digas-nada/11.jpg',
      '/images/no-digas-nada/12.jpg',
      '/images/no-digas-nada/13.jpg',
      '/images/no-digas-nada/14.jpg',
      '/images/no-digas-nada/15.jpg',
      '/images/no-digas-nada/16.jpg',
      '/images/no-digas-nada/17.jpg',
    ],
    title: 'No DIGAS NADA',
  },
  {
    imageSrc: '/images/libro5.jpg',
    marketSrc: 'https://tienda.juanrocha.co/',
    preview: [
      '/images/escorias/1.jpg',
      '/images/escorias/2.jpg',
      '/images/escorias/3.jpg',
      '/images/escorias/4.jpg',
      '/images/escorias/5.jpg',
      '/images/escorias/6.jpg',
      '/images/escorias/7.jpg',
      '/images/escorias/8.jpg',
      '/images/escorias/9.jpg',
      '/images/escorias/10.jpg',
      '/images/escorias/11.jpg',
    ],
    title: 'ESCORIAS',
  },
  {
    imageSrc: '/images/libro6.jpg',
    marketSrc: 'https://tienda.juanrocha.co/',
    preview: [
      'images/tiempos/1.jpg',
      'images/tiempos/2.jpg',
      'images/tiempos/3.jpg',
      'images/tiempos/4.jpg',
      'images/tiempos/5.jpg',
      'images/tiempos/6.jpg',
      'images/tiempos/7.jpg',
      'images/tiempos/8.jpg',
      'images/tiempos/9.jpg',
      'images/tiempos/10.jpg',
    ],
    title: 'TIEMPOS DE ABSTINENCIA',
  },
];
