import { listType } from './list.types';

export const theater: listType[] = [
  {
    imageSrc: '/images/capif.jpg',
    marketSrc: 'https://tienda.juanrocha.co/',
    preview: [
      '/images/las-capitalinas/01.png',
      '/images/las-capitalinas/02.png',
      '/images/las-capitalinas/03.png',
      '/images/las-capitalinas/04.png',
      '/images/las-capitalinas/05.png',
      '/images/las-capitalinas/06.png',
      '/images/las-capitalinas/07.png',
      '/images/las-capitalinas/08.png',
      '/images/las-capitalinas/1.png',
      '/images/las-capitalinas/2.png',
      '/images/las-capitalinas/3.png',
      '/images/las-capitalinas/4.png',
      '/images/las-capitalinas/5.png',
      '/images/las-capitalinas/6.png',
      '/images/las-capitalinas/7.png',
      '/images/las-capitalinas/8.png',
    ],
    title: 'Las Capitalinas',
  },
  {
    imageSrc: '/images/espejosf.jpg',
    marketSrc: 'https://tienda.juanrocha.co/',
    preview: [
      '/images/los-espejos/01.png',
      '/images/los-espejos/02.png',
      '/images/los-espejos/03.png',
      '/images/los-espejos/04.png',
      '/images/los-espejos/05.png',
      '/images/los-espejos/06.png',
      '/images/los-espejos/07.png',
      '/images/los-espejos/08.png',
      '/images/los-espejos/1.png',
      '/images/los-espejos/2.png',
      '/images/los-espejos/3.png',
      '/images/los-espejos/4.png',
      '/images/los-espejos/5.png',
      '/images/los-espejos/6.png',
      '/images/los-espejos/7.png',
      '/images/los-espejos/8.png',
      '/images/los-espejos/9.png',
      '/images/los-espejos/10.png',
      '/images/los-espejos/11.png',
      '/images/los-espejos/12.png',
      '/images/los-espejos/13.png',
      '/images/los-espejos/14.png',
      '/images/los-espejos/15.png',
    ],
    title: 'Los espejos y las variaciones',
  },
  {
    imageSrc: '/images/fosaf.jpg',
    marketSrc: 'https://tienda.juanrocha.co/',
    preview: [
      '/images/fosa/01.png',
      '/images/fosa/02.png',
      '/images/fosa/03.png',
      '/images/fosa/04.png',
      '/images/fosa/05.png',
      '/images/fosa/06.png',
      '/images/fosa/07.png',
      '/images/fosa/08.png',
      '/images/fosa/1.png',
      '/images/fosa/2.png',
      '/images/fosa/3.png',
      '/images/fosa/4.png',
      '/images/fosa/5.png',
      '/images/fosa/6.png',
      '/images/fosa/7.png',
      '/images/fosa/8.png',
    ],
    title: 'Fosa',
  },
  {
    imageSrc: '/images/hilosf.jpg',
    marketSrc: 'https://tienda.juanrocha.co/',
    preview: [
      '/images/hilos/01.png',
      '/images/hilos/02.png',
      '/images/hilos/03.png',
      '/images/hilos/04.png',
      '/images/hilos/05.png',
      '/images/hilos/06.png',
      '/images/hilos/07.png',
      '/images/hilos/08.png',
      '/images/hilos/1.png',
      '/images/hilos/2.png',
      '/images/hilos/3.png',
      '/images/hilos/4.png',
      '/images/hilos/5.png',
      '/images/hilos/6.png',
      '/images/hilos/7.png',
      '/images/hilos/8.png',
      '/images/hilos/9.png',
      '/images/hilos/10.png',
      '/images/hilos/11.png',
      '/images/hilos/12.png',
      '/images/hilos/13.png',
      '/images/hilos/14.png',
      '/images/hilos/15.png',
      '/images/hilos/16.png',
      '/images/hilos/17.png',
      '/images/hilos/18.png',
      '/images/hilos/19.png',
    ],
    title: 'Los hilos',
  },
  {
    imageSrc: '/images/visitantef.jpg',
    marketSrc: 'https://tienda.juanrocha.co/',
    preview: [
      '/images/visitante/01.png',
      '/images/visitante/02.png',
      '/images/visitante/03.png',
      '/images/visitante/04.png',
      '/images/visitante/05.png',
      '/images/visitante/06.png',
      '/images/visitante/07.png',
      '/images/visitante/08.png',
      '/images/visitante/1.png',
      '/images/visitante/2.png',
      '/images/visitante/3.png',
      '/images/visitante/4.png',
      '/images/visitante/5.png',
      '/images/visitante/6.png',
      '/images/visitante/7.png',
      '/images/visitante/8.png',
      '/images/visitante/9.png',
      '/images/visitante/10.png',
      '/images/visitante/11.png',
    ],
    title: 'El visitante y el recogedor de viento',
  },
  {
    imageSrc: '/images/pasof.jpg',
    marketSrc: 'https://tienda.juanrocha.co/',
    preview: [
      '/images/paso/01.png',
      '/images/paso/02.png',
      '/images/paso/03.png',
      '/images/paso/04.png',
      '/images/paso/05.png',
      '/images/paso/06.png',
      '/images/paso/07.png',
      '/images/paso/08.png',
      '/images/paso/1.png',
      '/images/paso/2.png',
      '/images/paso/3.png',
      '/images/paso/4.png',
      '/images/paso/5.png',
      '/images/paso/6.png',
      '/images/paso/7.png',
    ],
    title: 'El paso',
  },
];
